### PR TITLE
Fix table view

### PR DESCRIPTION
**Pull request by mandel59**
Fix https://github.com/AlexCovizzi/vscode-sqlite/issues/196.

### CODE REVIEW

**Review by thegardens — APPROVED** [review]
Reviewed w/o test

**Comment by AlexCovizzi** [comment]
Looks good and thanks a lot @mandel59 for the quick fix!

**Comment by dev-simonbailey** [comment]
Brilliant stuff...

**Comment by AngelaVilladiego** [comment]
Still not working for me on any version of VS Code

**Pull request merged**
