### PR TITLE
Activity Bar Icon 

### PR DESCRIPTION
**Pull request by PyKhaled**
untitled 2

### CODE REVIEW

**Comment by PyKhaled** [comment]
i need more help to active it by clicking on icon with command pallet

**Comment by PyKhaled** [comment]
i want to make it show all the time when click it check if there is no database open browse like command 'open database" do, if yes show it as explorer 

it is not final PR By the way

**Comment by AlexCovizzi** [comment]
I looked in the documentation for the vscode api but i did not find any way to know when the activity bar icon has been clicked.
Maybe you could try to add in the explorer bar (the one with the title SQLITE: SQLITE EXPLORER) an action to add a database.

**Comment by AlexCovizzi** [comment]
Or another idea, when vscode is opened check if there are databases in the workspace and then add every database found

**Comment by PyKhaled** [comment]
That what i was thinking

**Comment by AlexCovizzi** [comment]
You can search for the databases using ```workspace.findFiles```(like [here](https://github.com/AlexCovizzi/vscode-sqlite/blob/82801f587dbd365f3e40fa6629cd4c821f84c527/src/vscodewrapper/quickpick.ts#L49)) and then calling the function ```explorerAdd```(like [here](https://github.com/AlexCovizzi/vscode-sqlite/blob/82801f587dbd365f3e40fa6629cd4c821f84c527/src/extension.ts#L135)) in the databases found.

**Comment by AlexCovizzi** [comment]
Closed for inactivity

**Pull request closed without merging**
